### ISSUE TITLE
No display names on !atbboard board

### ISSUE THREAD

**Issue by ZacharyTalis** [ZacharyTalis/AltTextBot#15]
`Member left` for all board rankings instead of display names.

**Comment by Glossawy** [comment]
For posterity, Discord made significant changes to how events are received which also broke receiving message events at all originally. Updating javacord to `>3.1.0` fixed this but we should've looked into it more because the issue was Discord's new Gateway Intents system ([Javacord Wiki on Intents](https://javacord.org/wiki/basic-tutorials/gateway-intents.html#list-of-intents)). New Javacord enabled all non-privileged intents which let us get messages, but not privileged intents, which includes getting server member data, which requires Developer Portal changes.

Fixing this will just require enabling the `GUILD_MEMBERS` intent when connecting to the discord api gateway.
